apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0.4-alpine
          args:
            - "/usr/local/etc/redis/redis.conf"
            - "--appendonly"
            - "yes"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          volumeMounts:
            - name: conf
              mountPath: "/usr/local/etc/redis"
            - name: redis-storage
              mountPath: "/data"
      volumes:
        - name: conf
          secret:
            secretName: redis-conf
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
  selector:
    app: redis
