apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
  namespace: sns
  labels:
    app: subscriptions
spec:
  selector:
    matchLabels:
      app: subscriptions
  replicas: 1
  template:
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
      - name: subscriptions
        image: sns-subscriptions:latest
        ports:
        - containerPort: 3001
        env:
          - name: NODE_ENV
            value: "production"
          - name: CONFIG_DIR
            value: "/opt/sns/app/config"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-conf
                key: redis_password
        imagePullPolicy: "Never"
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /probes/liveness
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /probes/readiness
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptions
  namespace: sns
  labels:
    app: subscriptions
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: subscriptions
